const buat_login = function() {
    let x = document.getElementById("X");
    x.parentElement.removeChild(x);
    let p = document.createElement("P");
    p.className = "tulisan_login";
    p.innerHTML = "silahkan mendaftar";
    let element = document.getElementsByTagName("div")[0];
    element.appendChild(p);
    let form = document.createElement("form");
    element.appendChild(form);
    let label_user = document.createElement("label");
    form.appendChild(label_user);
    label_user.name = "nama";
    label_user.innerHTML = "Nama User";
    label_user.className = "label";
    let input_user = document.createElement("input");
    form.appendChild(input_user);
    input_user.name = "nama";
    input_user.className = "form_login";
    input_user.type = "text";
    input_user.placeholder = "Nama User..";
    let label_hp = document.createElement("label");
    form.appendChild(label_hp);
    label_hp.name = "HP";
    label_hp.innerHTML = "Nomor Handphone";
    label_hp.className = "label";
    let input_hp = document.createElement("input");
    form.appendChild(input_hp);
    input_hp.name = "HP";
    input_hp.className = "form_login";
    input_hp.type = "tel";
    input_hp.placeholder = "Nomor Handphone.";
    let label_email = document.createElement("label");
    form.appendChild(label_email);
    label_email.name = "email";
    label_email.innerHTML = "Username";
    label_email.className = "label";
    let input_email = document.createElement("input");
    form.appendChild(input_email);
    input_email.name = "email";
    input_email.className = "form_login";
    input_email.type = "email";
    input_email.placeholder = "Username atau Email";
    let label_password = document.createElement("label");
    form.appendChild(label_password);
    label_password.name = "password";
    label_password.innerHTML = "Password";
    label_password.className = "label";
    let input_password = document.createElement("input");
    form.appendChild(input_password);
    input_password.name = "password";
    input_password.className = "form_login";
    input_password.type = "password";
    input_password.placeholder = "Password";
    let button_ok = document.createElement("button");
    form.appendChild(button_ok);
    button_ok,type = "button";
    button_ok.className = "tombol_login";
    button_ok.innerHTML = "daftar sekarang";
}